version: '3.9'

services:

  calculate:
    image: tarasssito/ucu-ds-streams-calculate
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      TOPIC: ${TOPIC}

  generation:
    image: tarasssito/ucu-ds-streams-generation
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      TOPIC: ${TOPIC}
    depends_on:
      - calculate

networks:
  default:
    name: kafka_default

